###############################
#  Violetshine's .zshrc file  #
###############################

### zsh options (https://zsh.sourceforge.io/Doc/Release/Options.html) ###

# "If a completion is performed with the cursor within a word, and a full completion is inserted, the cursor is moved to
# the end of the word. That is, the cursor is moved to the end of the word if either a single match is inserted or menu
# completion is performed."
setopt always_to_end

# "If set, parameter expansion, command substitution and arithmetic expansion are performed in prompts. Substitutions
# within prompts do not affect the command status."
setopt prompt_subst

############################

# nix already places itself in /etc/

# Hook direnv (installed through nix profile)
eval "$(direnv hook zsh)"

# Homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

# GPG
export GPG_TTY=$(tty)

### PATH additions ###

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# Rust/Cargo
export PATH="$HOME/.cargo/bin:$PATH"

# GHCup (Haskell & related tools)
[ -f "$HOME/.ghcup/env" ] && . "$HOME/.ghcup/env" # ghcup-env

# Add ~/.local/bin to path
export PATH="$HOME/.local/bin:$PATH"

### Custom zsh prompt ###
PROMPT=$'\e[38;5;92m%n\e[0m %~ %# '
